stages:
- name: get_pre_trained_embeddings
  embedding_type: glove.6B.100d


### list of possible options for embedding_type:
# 'charngram.100d'
# 'fasttext.en.300d', 'fasttext.simple.300d'
# 'glove.42B.300d', 'glove.840B.300d'
# 'glove.twitter.27B.25d', 'glove.twitter.27B.50d', 'glove.twitter.27B.100d', 'glove.twitter.27B.200d'
# 'glove.6B.50d', 'glove.6B.100d', 'glove.6B.200d', 'glove.6B.300d'
