batch_size: 100
embedding_size: 5
hidden_size: 2
learning_rate: 1
learning_rate_decay: 0.85
max_norm: 1
max_init_param: 0.1
number_of_layers: 1
sequence_length: 30
dropout_probability: 0.4
lstm_configuration: default
device: gpu
