batch_size: 100
embedding_size: 100
hidden_size: 100
learning_rate: 0.5
learning_rate_decay: 0.8
max_init_param: 0.05
max_norm: 15
number_of_layers: 2
sequence_length: 30
dropout_probability: 0.5
lstm_configuration: res-var-emb
device: gpu
