batch_size: 50
embedding_size: 100
learning_rate: 1
learning_rate_decay: 0.85
max_norm: 10
max_init_param: 0.5
number_of_layers: 2
sequence_length: 30
dropout_probability: 0.2
lstm_configuration: var-emb
device: gpu
