batch_size: 80
embedding_size: 100
hidden_size: 100
learning_rate: 0.1
learning_rate_decay: 0.8
max_norm: 8
max_init_param: 0.05
number_of_layers: 2
sequence_length: 30
dropout_probability: 0.6
lstm_configuration: var-emb
device: gpu
