batch_size: 80
embedding_size: 50
hidden_size: 50
learning_rate: 1
learning_rate_decay: 0.85
max_norm: 4 
max_init_param: 0.05
number_of_layers: 1
sequence_length: 30
dropout_probability: 0.6
lstm_configuration: res-var-emb
device: gpu
