batch_size: 80
embedding_size: 50
hidden_size: 50
learning_rate: 0.5
learning_rate_decay: 0.8
max_norm: 3
max_init_param: 0.05
number_of_layers: 1
sequence_length: 30
dropout_probability: 0.6
lstm_configuration: var-emb
device: gpu
