stages:
- name: pre_process
  input_file: train.txt
  output_file: pre_processed.train.txt
- name: pre_process
  input_file: test.txt
  output_file: pre_processed.test.txt
- name: pre_process
  input_file: valid.txt
  output_file: pre_processed.valid.txt

- name: dictionary_creation
  input_file: pre_processed.train.txt
  frequency_threshold: 3

- name: apply_dictionary
  input_file: pre_processed.train.txt
  output_file: tokens.train.pkl
- name: apply_dictionary
  input_file: pre_processed.test.txt
  output_file: tokens.test.pkl
- name: apply_dictionary
  input_file: pre_processed.valid.txt
  output_file: tokens.valid.pkl

- name: train_rnn_model
  training_config_file: rnn_training_config.yaml
  model_config_file: wiki_rnn_model_config.yaml
  train_file: tokens.train.pkl
  valid_file: tokens.valid.pkl
  test_file: tokens.test.pkl
